### ISSUE TITLE
Update to knplabs github api 2.0

### ISSUE THREAD

**Issue by skluck** [hal-platform/hal#4]
Github API package updated to 2.0 which supports newer versions of guzzle - https://github.com/KnpLabs/php-github-api

**Comment by nagibyro** [comment]
knplabs github 2.0 uses [HTTP Plug](http://httplug.io/) -- The caching for the github client is now a PSR-6 cache object as it just uses the [cache plugin](http://docs.php-http.org/en/latest/plugins/cache.html) under the hood. The good news is that the cache key is created off the http method and the PSR7 `UriInterface` -- which will include the query parameters. So we won't need to extend the client with our own caching. However since MCP-Cache is not PSR6 compatible we would need to pull in a different cache library.

For cache we can either pull in another caching library that uses predis and PSR6 interfaces [this](https://github.com/php-cache/predis-adapter) one seems like a good candidate -- or we write our own [HTTP Plugin](http://docs.php-http.org/en/latest/plugins/build-your-own.html) that uses MCP cache. We'd have to add the cache plugin manually to the client and would not be able to use the `addCache()` or `removeCache()` methods on the github client.

**Comment by skluck** [comment]
Maybe writing our own PSR-12 cache plugin for http plug is the way to go. I say give that a shot first. It's just a few hundred lines of code and we would just need to change cache item usage to the simpler PSR-12 interface.

https://github.com/php-http/cache-plugin

**Comment by nagibyro** [comment]
PR's opened for the Agent and UI

**Comment by skluck** [comment]
Merged into master
- Showing download progress of GitHub archives was dropped since the http client (httplug) doesn't support events.
